server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://192.168.99.100:9200" ]
#monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials

elasticsearch.username: elastic
elasticsearch.password: elastic
